build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19
labels:
  org.opencontainers.image.title: "rtl_433 Home Assistant Add-on"
  org.opencontainers.image.description: "Receive wireless sensor data via an SDR dongle and rtl_433"
  org.opencontainers.image.source: "https://github.com/catduckgnaf/rtl_433_haos_addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  rtl433GitRevision: master
