name: rtl_433
version: "2024.1.0"
description: Receive wireless sensor data via an SDR dongle and rtl_433
slug: rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon
init: false 
arch:
- armv7
- aarch64
- amd64
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
options:
  rtl_433_conf_file: "/config/rtl_433/rtl_433.conf"
  discovery: false
  rtl_device_id_1: 
  rtl_device_id_2:
  rtl_device_id_2: 
  rtl_device_id_2: 
  rtl_device_id_2: 
  rtl_device_id_2:
  rtl_device_id_2: 
  rtl_device_id_2: 
schema:
  rtl_433_conf_file: "str?"
  discovery: bool
  rtl_device_id_1: int
  rtl_device_id_2:
  rtl_device_id_2: 
  rtl_device_id_2: 
  rtl_device_id_2: 
  rtl_device_id_2:
  rtl_device_id_2: 
  rtl_device_id_2: 