name: rtl_433
version: "2024.2.8"
description: Receive wireless sensor data via an SDR dongle and rtl_433
slug: rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon
init: false 
arch:
- armv7
- aarch64
- amd64
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
options:
  rtl_433_conf_file: "/config/rtl_433/rtl_433.conf"
  discovery: false
  discovery_retain: true
  discovery_force_update: false
  discovery_host: "core-mosquitto"
  discovery_port: 1883
  discovery_user: ""
  discovery_password: ""
  discovery_topic: "rtl_433/+/events"
  discovery_prefix: "homeassistant"
  device_topic_suffix: ""
  discovery_interval: 600
  discovery_ids: 24 69
  discovery_log_level: "default"

  other_args: ""

schema:
  rtl_433_conf_file: "str?"
  discovery: bool?
  discovery_ids: "str?"
  discovery_log_level: "list(default|quiet|debug)"
