name: rtl_433
version: "2023.12.0"
description: Receive wireless sensor data via an SDR dongle and rtl_433
slug: rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon
init: false 
arch:
- armv7
- aarch64
- amd64
ports:
  9433/tcp: 9433
ports_description:
  9433/tcp: Add-On Communication
host_network: true
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
options:
  rtl_433_conf_file: "/config/rtl_433/rtl_433.conf"
  output_options: "mqtt"
  host: "core-mosquitto"
  port: 1883
schema:
  rtl_433_conf_file: "str?"
  host: str?
  port: int
  output_options: list(websocket|mqtt|custom)?
