name: rtl_433
version: "2023.11.1.1"
description: Receive wireless sensor data via an SDR dongle and rtl_433
slug: rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon/tree/main/rtl_433
init: false 
arch:
- armv7
- aarch64
- amd64
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
ports:
  8443/tcp: 8443
ports_description:
  8443/tcp: Websocket port
options:
  rtl_433_conf_file: "/config/rtl_433/rtl_433.conf"
  output_options: "websocket"
  log_level: list(default|quiet|debug)
  mqtt:
    server: core-mosquitto
    user: addon
    password: 
    retain: true
    rtl_topic: "rtl_433/+/events"
    discovery_prefix: "homeassistant"
    discovery_interval: 600
schema:
  rtl_433_conf_file": "str?"
  output_options: list(websocket|mqtt)
  log_level: "default"
  ws_http_host: "str?"
  ws_http_port: int
  mqtt:
   mqtt_host: "str?"
   mqtt_port: int
   mqtt_user: "str?"
   mqtt_password: "str?"
   retain: bool
   rtl_topic: str
   discovery_prefix: "str?"
   discovery_interval: int

