name: rtl_433
version: "2023.11.3"
description: Receive wireless sensor data via an SDR dongle and rtl_433
slug: rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon/tree/main/rtl_433
init: false 
arch:
- armv7
- aarch64
- amd64
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
ports: 
  9433/tcp: 9433
options:
  rtl_433_conf_file: "/config/rtl_433/rtl_433.conf"
 # rtl_433_http_script": "/config/rtl_433/rtl_433_http.py" Was testing, removing for now
 # rtl_433_mqtt_script": "/config/rtl_433/rtl_433_mqtt.py"
  output_options: "websocket"
 # run_http_script: false Was testing, removing for now
 # run_mqtt_script: false Was testing, removing for now
 # mqtt_host: "core-mosquitto"
 # mqtt_port: 1883
 # mqtt_user: "addons"
 # mqtt_password: ""
 # retain: true
  log_level: "default"
schema:
  rtl_433_conf_file": "str?"
 # rtl_433_http_script": "str?" Was testing, removing for now
 # rtl_433_mqtt_script": "str?" Was testing, removing for now
#  run_http_script: bool Was testing, removing for now
#  run_mqtt_script: bool Was testing, removing for now
  output_options: list(websocket|mqtt)
#  mqtt_host: "str?"
#  mqtt_port: int
#  mqtt_user: "str?"
 # mqtt_password: "str?"
 # retain: bool
  log_level: list(default|quiet|debug)
