name: rtl_433
version: "2023.11.1.1"
description: Receive wireless sensor data via an SDR dongle and rtl_433
slug: rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon/tree/main/rtl_433
init: false 
arch:
- armv7
- aarch64
- amd64
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
options:
  rtl_433_conf_file: "/config/rtl_433/rtl_433.conf"
  output_options: "websocket"
  mqtt_host: 
  mqtt_port:
  mqtt_user:
  mqtt_password:
  retain: true
  log_level: "default"
schema:
  rtl_433_conf_file": "str?"
  output_options: list(websocket|mqtt)
  mqtt_host: "str?"
  mqtt_port: int
  mqtt_user: "str?"
  mqtt_password: "str?"
  retain: bool
  rtl_topic: str
  discovery_prefix: "str?"
  discovery_interval: int
  log_level: list(default|quiet|debug)

