name: Build rtl_433 images

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_rtl_433:
    name: Build rtl_433 addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64, i386]
        addon: [rtl_433, rtl_433-next, rtl_433_mqtt_autodiscovery, rtl_433_mqtt_autodiscovery-next]

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy files for next if needed
      run: |
        if [ "${{ matrix.addon }}" == "rtl_433-next" ]; then
          cp -nv -R rtl_433/* ${{ matrix.addon }}/
        fi
        if [ "${{ matrix.addon }}" == "rtl_433_mqtt_autodiscovery-next" ]; then
          cp -nv -R rtl_433_mqtt_autodiscovery/* ${{ matrix.addon }}/
        fi

    - name: Build ${{ matrix.addon }} ${{ matrix.arch }} image
      uses: home-assistant/builder@master
      if: github.event.pull_request.head.repo.full_name != github.repository
      with:
        args: |
          --test \
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-${{ matrix.addon }}-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target ${{ matrix.addon }}

    - name: Build and push ${{ matrix.addon }} ${{ matrix.arch }} image
      uses: home-assistant/builder@master
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        args: |
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-${{ matrix.addon }}-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target ${{ matrix.addon }}
